### ISSUE TITLE
Show all emoji and reduce size

### ISSUE THREAD

**Issue by nhatnam09nl** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#14]
It looks very nice but can't integrate. It is too large (it should be less than 200KB). They need to be converted to webp format. And svg format is required to display all as static. We can refer here: https://googlefonts.github.io/noto-emoji-animation/

**Comment by Tarikul-Islam-Anik** [comment]
These are APNG files without any compression. I tried to convert it to WebP format, but it lost the animation. I'm not planning to display them as static. The static version of these emojis in SVG format is available on [microsoft/fluentui-emoji](https://github.com/microsoft/fluentui-emoji/tree/main/assets).

**Comment by nhatnam09nl** [comment]
> These are APNG files without any compression. I tried to convert it to WebP format, but it lost the animation. I'm not planning to display them as static. The static version of these emojis in SVG format is available on [microsoft/fluentui-emoji](https://github.com/microsoft/fluentui-emoji/tree/main/assets).

Thanks. How can we access svg from link like png(https://raw.githubusercontent.com/Tarikul-Islam-Anik/Microsoft-Teams-Animated-Emojis/master/Emojis/Travel%20and%20places/Star.png)?
