### ISSUE TITLE
Request to Add License for Animated Emojis

### ISSUE THREAD

**Issue by avexperi** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#15]
Hi there! I noticed that the repository currently does not have a license specified. I'd like to request that you add a clear open-source license, like the MIT License, to the repository. This will help users like me understand the terms under which we can use the animated emojis, and it will ensure that usage is legal and compliant. Thanks for considering this request!

**Comment by Tarikul-Islam-Anik** [comment]
@avexperi Thanks for pointing it out. It's been added.
