### ISSUE TITLE
Women in Technology emoji aren't animated

### ISSUE THREAD

**Issue by aj11anuj** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#19]
Some emoji's i found aren't animated for example (Women in Technology emoji in [this repo](https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/tree/master/Emojis/People%20with%20professions)).

**Comment by aj11anuj** [comment]
> Hello, @aj11anuj! Hope you're doing well. Unfortunately, it's not possible to get all emojis animated. Some are animated, some aren't. I tried my best to expand the animated emoji library.

It may not be possible to animate all, but i think this one can be animated as it's counter part (Man in Technology) is animated.

**Comment by Tarikul-Islam-Anik** [comment]
Probably in the next update, we may get most of them animated.
