### ISSUE TITLE
download animated

### ISSUE THREAD

**Issue by kittenvr** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#20]
how do i download the animated emojis, if i click the button its not animated

**Comment by Tarikul-Islam-Anik** [comment]
Hello, @kittenvr!
I hope you're doing well. The files you're downloading are animated files formatted as **APNG**. For some reason, if you open these APNG files with any photo viewer application (for example, Windows' photo app), then it won't work as expected. I mean, you won't see any animations. However, if you use the files directly in any project, they'll be animated.

If you still want to see a live preview locally, just drag and drop the APNG file into any browser's new tab. I hope this might help.
