### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by dearDreamWeb** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#26]
![image](https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/assets/52070630/47f1ab57-576c-4833-bf6b-ebef2ce3e6a7)

**Comment by Tarikul-Islam-Anik** [comment]
Hello @dearDreamWeb, 
Thanks for reporting. However, I check and it's working as expected from my side. Can you recheck again?

**Comment by dearDreamWeb** [comment]
No problem

**Comment by dearDreamWeb** [comment]
This problem occurs again

**Comment by Tarikul-Islam-Anik** [comment]
Hey @dearDreamWeb, could you do me a favor and take a screenshot of your console log if this happens again? Thanks!

**Comment by dearDreamWeb** [comment]
ok

**Comment by dearDreamWeb** [comment]
I found the reason. It's because of my browser's network proxy plug-in.

**Comment by Tarikul-Islam-Anik** [comment]
@dearDreamWeb Thanks for sharing the cause. I guess you solved it from your end. So, I'm closing the issue. Thank you.
