### ISSUE TITLE
Animated Webp version

### ISSUE THREAD

**Issue by bugrevealingbme** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#7]
I am using Flutter and there is no Apng support. But awebp support is available. Can you also upload the outputs as webp? Or can you review which type to choose for the default version? Thanks

**Comment by Tarikul-Islam-Anik** [comment]
Hello, @bugrevealingbme!
Actually, I haven't tried the **WebP** format. I'll check. If the results are good enough, I'll consider uploading in **WebP** format.
